### ISSUE TITLE
How is this generated?

### ISSUE THREAD

**Issue by amalon** [windows31/hoganfamtrains-bedrock#1]
Hi, This is awesome. I haven't been able to try as I don't have bedrock to test on, but I have bedrock players who connect via geyser so would definitely be interested in using myself (and integrating with hoganfam-trains if it makes sense to do so).

If you don't mind me asking, how is this pack generated? I presume there's some automated tool that does it from the java edition resource pack?

**Comment by windows31** [comment]
The pack is generated using the converter found on the official GeyserMC discord server. I have just changed the mappings file so the trains actually work as without it they don't work and have edited a few other files to retain compatibility with other packs generated via the converter. You can try it out yourself if you want. I plan on updating this whenever a new release on hoganfam-trains is made

**Comment by windows31** [comment]
Issue resolved
